"use client";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";
import { store } from "@/lib/redux/store";
import { Provider } from "react-redux";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Social media app",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <Provider store={store}>
            <Navbar />
            {children}
          </Provider>
          <Toaster />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
